apiVersion: v1
kind: Service
metadata:
  name: db-con
spec:
  selector:
    app: api2
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017
  externalIPs:
    - 34.231.222.174
